version: '3'
services:
  webapp: 
    build: .
    container_name: myapp_practica
    ports:
      - "83:3000"
    networks:
      - network_practica
  prometheus:
    image: prom/prometheus:v2.20.1
    container_name: prometheus_practica
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    depends_on:
      - webapp
    links:
      - webapp
    networks:
      - network_practica
    command: --config.file=/etc/prometheus/prometheus.yml
  grafana:
      depends_on:
          - prometheus
      ports:
          - "3500:3000"
      container_name: grafana_practica
      image: "grafana/grafana:7.1.5"
      environment: 
          - GF_AUTH_DISABLE_LOGIN_FORM=true
          - GF_AUTH_ANONYMOUS_ENABLED=true
          - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
          - GF_INSTALL_PLUGINS=grafana-clock-panel 1.0.1
      networks: 
          - network_practica
      volumes:
          - "myGrafanaVol:/var/lib/grafana"
          - "./grafana:/etc/grafana/provision/datasources"
volumes:
  myGrafanaVol: 
networks:
  network_practica: